on: [push, pull_request]

name: check-and-test

jobs:
  armv7-glibc:
    name: Ubuntu 18.04 (for ARMv7 - glibc)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true

      - name: Install binutils-arm-none-eabi
        run: |
          sudo apt-get update
          sudo apt-get install binutils-arm-none-eabi
      
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check
          args:  --target=armv7-unknown-linux-gnueabihf

  ubuntu-glibc:
    name: Ubuntu 18.04 - glibc
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
